"use client";
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,ChevronRight,Clock3,Copy,Grid2X2,MapPin,Minus,Plus,ShoppingBag,Trash2,X,Snowflake,Package} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Checkbox} from '@/components/ui/checkbox';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {catalogVersion,families,forFamily,getVariant,money,photoUrl,points,typeLabel} from '@/shared/catalog.mjs';
import {moscowDate,priceItem,priceCart,validateOrder,orderText} from '@/shared/order.mjs';
import {getTelegram,authenticatedLaunch} from './telegram';
import {submitOrder,reuseRequest} from '@/shared/submit.mjs';
type Item={variantId:string;quantity:number;design:string;berry:string;inscription:string};
type Family=typeof families[number];
type View='catalog'|'cart'|'pickup';
const CART_KEY='deli-berry-cart-'+catalogVersion;
const PENDING_KEY='deli-berry-request-'+catalogVersion;

function ProductImage({id,name,priority=false}:{id:string;name:string;priority?:boolean}){
 const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[id]);
 if(!id||failed)return <div className="quantity-art" aria-label={name}><Package size={30}/><strong>{!id?'25':'Дели Берри'}</strong><span>{!id?'ягод в шоколаде':'Фото недоступно'}</span>{!id&&<small>Крафтовая коробка</small>}</div>;
 return <img src={photoUrl(id)} alt={name} width={1254} height={1254} loading={priority?'eager':'lazy'} decoding="async" onError={()=>setFailed(true)}/>;
}
function Stepper({value,onChange,label}:{value:number;onChange:(v:number)=>void;label:string}){return <div className="stepper"><button type="button" aria-label={'Уменьшить '+label} onClick={()=>onChange(value-1)} disabled={value<=1}><Minus size={17}/></button><span aria-live="polite">{value}</span><button type="button" aria-label={'Увеличить '+label} onClick={()=>onChange(value+1)} disabled={value>=99}><Plus size={17}/></button></div>;}

export default function CatalogApp(){
 const standalone=typeof document!=='undefined'&&document.documentElement.dataset.orderMode==='copy';
 const [view,setView]=useState<View>('catalog'),[category,setCategory]=useState('all'),[type,setType]=useState('fresh');
 const [cart,setCart]=useState<Item[]>([]),[loaded,setLoaded]=useState(false),[selected,setSelected]=useState<Family|null>(null),[draft,setDraft]=useState<Item|null>(null);
 const [withText,setWithText]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const [point,setPoint]=useState(''),[date,setDate]=useState(''),[time,setTime]=useState(''),[comment,setComment]=useState('');
 const [review,setReview]=useState(''),[payload,setPayload]=useState(''),[canSend,setCanSend]=useState(false),[sending,setSending]=useState(false);
 const [sentId,setSentId]=useState(''),sendingRef=useRef(false);
 useEffect(()=>{
  try{const saved=JSON.parse(localStorage.getItem(CART_KEY)||'[]');if(Array.isArray(saved)&&saved.length<=20)setCart(saved.filter(i=>{try{priceItem(i);return true;}catch{return false;}}));}catch{}
  setLoaded(true);let attempts=0;
  if(!document.querySelector('script[data-telegram-sdk]')){const script=document.createElement('script');script.src='https://telegram.org/js/telegram-web-app.js';script.async=true;script.dataset.telegramSdk='true';document.head.appendChild(script);}
  const initialize=()=>{const tg=getTelegram();if(tg){tg.ready();tg.expand();tg.setHeaderColor?.('#ffffff');tg.setBackgroundColor?.('#ffffff');setCanSend(!standalone&&authenticatedLaunch());return true;}return false;};
  if(!initialize()){const timer=setInterval(()=>{if(initialize()||++attempts>=20)clearInterval(timer);},250);return()=>clearInterval(timer);}
 },[]);
 useEffect(()=>{if(loaded)try{localStorage.setItem(CART_KEY,JSON.stringify(cart));}catch{}},[cart,loaded]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(timer);},[notice]);
 useEffect(()=>{const back=getTelegram()?.BackButton;if(!back)return;const go=()=>{if(sendingRef.current)return;if(review){setReview('');setSentId('');}else if(selected)setSelected(null);else setView('catalog');};if(selected||review||view!=='catalog')back.show();else back.hide();back.onClick(go);return()=>back.offClick(go);},[view,selected,review,canSend]);
 const count=cart.reduce((n,i)=>n+i.quantity,0),total=cart.length?priceCart(cart).total:0;
 const navigate=(target:View)=>{setView(target);setError('');window.scrollTo({top:0,behavior:'instant'});};
 const open=(family:Family)=>{const v=forFamily(family.id,type)[0]||forFamily(family.id)[0];setDraft({variantId:v.id,quantity:1,design:v.photo,berry:v.includedBerry?'included':'none',inscription:''});setSelected(family);setWithText(false);setError('');};
 const chooseVariant=(id:string)=>{const v=getVariant(id);setDraft(d=>d?{...d,variantId:id,design:v.photo,berry:v.includedBerry?'included':d.berry==='included'?'none':d.berry}:null);};
 const add=()=>{if(!draft)return;if(withText&&!draft.inscription.trim()){setError('Напишите текст шоколадной надписи.');return;}if(cart.length>=20){setError('В одной заявке — до 20 разных позиций.');return;}const clean={...draft,inscription:withText?draft.inscription.trim():''};priceItem(clean);setCart([...cart,clean]);setSelected(null);setNotice('Добавлено в корзину');getTelegram()?.HapticFeedback?.notificationOccurred('success');};
 const prepare=(event:React.FormEvent)=>{event.preventDefault();if(sendingRef.current)return;setError('');try{const form=new FormData(event.currentTarget as HTMLFormElement);const data={version:catalogVersion,items:cart,point,date:String(form.get('date')||''),time:String(form.get('time')||''),comment:String(form.get('comment')||'')};let previous=payload;try{previous=localStorage.getItem(PENDING_KEY)||previous;}catch{}const input=reuseRequest(data,previous,globalThis.crypto?.randomUUID?.()||('order-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,12)));const order=validateOrder(input);const json=JSON.stringify(input);try{localStorage.setItem(PENDING_KEY,json);}catch{}setPayload(json);setReview(orderText(order));setSending(false);setSentId('');}catch(e){setError(e instanceof Error?e.message:'Проверьте данные заявки.');}};
 const send=async()=>{if(sendingRef.current||sentId)return;sendingRef.current=true;setError('');setSending(true);try{const tg=getTelegram();if(!tg?.initData)throw new Error('Откройте каталог кнопкой Telegram-бота или скопируйте заявку.');validateOrder(JSON.parse(payload));const result=await submitOrder(JSON.parse(payload),tg.initData);setSentId(result.orderId);setCart([]);setPayload('');try{localStorage.removeItem(PENDING_KEY);}catch{}setNotice('Заявка передана менеджеру');getTelegram()?.HapticFeedback?.notificationOccurred('success');}catch(e){setError(e instanceof Error?e.message:'Не удалось передать заявку.');}finally{sendingRef.current=false;setSending(false);}};
 const copy=async()=>{try{await navigator.clipboard.writeText(review);setNotice('Заявка скопирована');}catch{setError('Выделите и скопируйте текст заявки ниже.');}};
 const activeVariant=draft?getVariant(draft.variantId):null,draftTotal=draft?priceItem({...draft,inscription:withText?draft.inscription:''}).total:0;
 return <div className="app-shell">
  <header className="app-header"><button className="brand" onClick={()=>navigate('catalog')} aria-label="Дели Берри — каталог"><span>Дели Берри<span className="brand-dot">.</span></span><small>Клубника в шоколаде</small></button><button className="icon-button cart-button" onClick={()=>navigate('cart')} aria-label={`Корзина, товаров: ${count}`}><ShoppingBag size={24}/>{count>0&&<b>{count}</b>}</button></header>
  <main>{view==='catalog'&&<>
   <div className="catalog-heading"><h1>Выберите свой подарок</h1><span>Наборы и букеты</span></div>
   <Tabs value={category} onValueChange={setCategory} className="category-tabs"><TabsList aria-label="Категории товаров"><TabsTrigger value="all">Все</TabsTrigger><TabsTrigger value="sets">Наборы</TabsTrigger><TabsTrigger value="bouquets">Букеты</TabsTrigger></TabsList>
    <RadioGroup className="type-options" value={type} onValueChange={setType} aria-label="Вид клубники">{[['fresh','Свежая'],['fd','Сублимированная']].map(([value,label])=><label className={type===value?'type-option selected':'type-option'} key={value}><RadioGroupItem value={value}/><span>{label}</span></label>)}</RadioGroup>
    <div className="preparation">{type==='fresh'?<Clock3 size={19}/>:<Snowflake size={19}/>}<p>{type==='fresh'?'Готовим после заказа, от 20 минут':'Готовые наборы можно забрать сразу'}<small>{type==='fresh'?'Точное время зависит от заказа':'Наличие выбранного оформления подтвердим'}</small></p></div>
    {['all','sets','bouquets'].map(cat=><TabsContent value={cat} key={cat}><div className="product-grid">{families.filter(f=>(cat==='all'||f.category===cat)&&forFamily(f.id,type).length>0).map((family,index)=>{const v=forFamily(family.id,type)[0];return <article className="product-card" key={family.id}><button className="product-photo" onClick={()=>open(family)} aria-label={`Открыть ${family.name}`}><ProductImage id={family.photo} name={family.name} priority={index<2}/></button><div className="product-meta"><small>{family.id==='MIX-BANANA'?'12 ягод + 2 банана':family.id==='SET-25'?'Крафтовая коробка':'Пример оформления'}</small><h2><button onClick={()=>open(family)}>{family.shortName}</button></h2><div className="price-row"><strong>{money(v.price)}</strong><button className="add-button" aria-label={`Выбрать ${family.name}`} onClick={()=>open(family)}><Plus size={21}/></button></div></div></article>;})}</div></TabsContent>)}
   </Tabs><div className="catalog-bottom"><MapPin size={19}/><p>Две точки. Один каталог.<small>Discovery и Зеленопарк · одинаковые цены</small></p><button className="icon-button" onClick={()=>navigate('pickup')} aria-label="Условия получения"><ChevronRight size={20}/></button></div>
  </>}
  {view==='cart'&&<section className="cart-page"><div className="page-title"><h1>Корзина</h1><span>{count?count+' шт.':''}</span></div>{!cart.length?<div className="empty-state"><ShoppingBag size={48} strokeWidth={1.2}/><h2>Что положим в коробку?</h2><p>Выберите набор или букет.<br/>Оформление и дополнения — в карточке.</p><button className="primary" onClick={()=>navigate('catalog')}>Открыть каталог<ArrowRight size={18}/></button></div>:<>
   <div className="cart-lines">{cart.map((item,index)=>{const l=priceItem(item);return <article className="cart-line" key={index}><div className="cart-thumbnail"><ProductImage id={item.design} name={l.family.name}/></div><div className="cart-item-body"><div className="cart-name"><h2>{l.family.shortName}</h2><button className="remove" aria-label={'Удалить '+l.family.shortName} onClick={()=>setCart(cart.filter((_,i)=>i!==index))}><Trash2 size={17}/></button></div><p>{typeLabel(l.variant.type)}</p>{l.berry!=='none'&&<small>{l.berry==='included'?'Ягодное украшение включено':l.berry==='blueberry'?'Голубика +200 ₽':'Малина +200 ₽'}</small>}{l.inscription&&<small>Надпись: «{l.inscription}» · +250 ₽</small>}<div className="cart-line-bottom"><Stepper value={item.quantity} onChange={quantity=>setCart(cart.map((a,i)=>i===index?{...a,quantity}:a))} label={l.family.shortName}/><strong>{money(l.total)}</strong></div></div></article>;})}</div>
   <button className="text-button continue-shopping" onClick={()=>navigate('catalog')}><Plus size={17}/> Добавить ещё</button>
   <form onSubmit={prepare} className="checkout-form"><h2>Где и когда заберёте?</h2><RadioGroup value={point} onValueChange={setPoint} className="pickup-options" aria-label="Точка получения">{points.map(p=><label key={p.id} className={point===p.id?'pickup-option selected':'pickup-option'}><MapPin size={20}/><span>{p.name}</span><RadioGroupItem value={p.id}/></label>)}</RadioGroup><div className="date-time"><label>Дата получения<input name="date" type="date" required min={moscowDate()} value={date} onInput={e=>setDate(e.currentTarget.value)} onChange={e=>setDate(e.target.value)}/></label><label>Время, МСК<input name="time" type="time" required value={time} onInput={e=>setTime(e.currentTarget.value)} onChange={e=>setTime(e.target.value)}/></label></div><p className="field-help">Укажите желаемое время — подтвердим его при оформлении.</p><label className="comment-label">Пожелания к оформлению <span>необязательно</span><textarea name="comment" value={comment} maxLength={500} onChange={e=>setComment(e.target.value)} placeholder="Цвета, повод, детали оформления…" rows={3}/></label><div className="total-row"><span>Итого</span><strong>{money(total)}</strong></div><p className="checkout-note">Полное оформление и стоимость согласуем перед оплатой. Заказ к дате и времени — по полной предоплате.</p>{error&&<p role="alert" className="error-message">{error}</p>}<button className="primary checkout-button" type="submit">Сформировать заявку<ArrowRight size={19}/></button></form>
  </>}</section>}
  {view==='pickup'&&<section className="pickup-page"><h1>Получение заказа</h1><p className="intro">Выберите удобную точку в корзине.</p><div className="location-list">{points.map(p=><div className="location-row" key={p.id}><MapPin size={23}/><div><h2>{p.name}</h2><p>Весь действующий ассортимент к заказу</p></div></div>)}</div><div className="info-section"><Clock3 size={23}/><div><h2>Свежая клубника</h2><p>Изготавливаем после заказа, от 20 минут. Точное время зависит от заказа.</p></div></div><div className="info-section"><Snowflake size={23}/><div><h2>Сублимированная клубника</h2><p>Готовые наборы и букеты можно забрать сразу. Наличие конкретного оформления подтвердим при заказе.</p></div></div><div className="info-section"><ShoppingBag size={23}/><div><h2>К нужной дате</h2><p>Укажите дату и время получения. Такой заказ оформляется по полной предоплате, после согласования деталей.</p></div></div><button className="primary" onClick={()=>navigate(cart.length?'cart':'catalog')}>{cart.length?'Перейти в корзину':'Выбрать подарок'}<ArrowRight size={18}/></button></section>}
  </main><nav className="bottom-nav" aria-label="Основная навигация">{([{id:'catalog',label:'Каталог',Icon:Grid2X2},{id:'cart',label:'Корзина',Icon:ShoppingBag},{id:'pickup',label:'Получение',Icon:MapPin}] as const).map(({id,label,Icon})=><button key={id} onClick={()=>navigate(id)} className={view===id?'active':''} aria-current={view===id?'page':undefined}><span><Icon size={22}/>{id==='cart'&&count>0&&<b>{count}</b>}</span>{label}</button>)}</nav>
  <Sheet open={!!selected} onOpenChange={isOpen=>{if(!isOpen)setSelected(null);}}><SheetContent side="bottom" className="product-sheet" showCloseButton={false}>{selected&&draft&&activeVariant&&<>
   <div className="sheet-top"><button className="back-button" onClick={()=>setSelected(null)}><ArrowLeft size={21}/> Каталог</button><button className="icon-button" aria-label="Закрыть карточку" onClick={()=>setSelected(null)}><X size={21}/></button></div><div className="product-detail-scroll"><div className="detail-photo"><ProductImage id={draft.design} name={selected.name} priority/></div><div className="detail-body"><SheetDescription className="photo-caption">{selected.photo?'Пример оформления':'Набор в крафтовой коробке'}{activeVariant.type==='fd'?' · фото свежей линии':''}</SheetDescription><SheetTitle className="detail-title">{selected.name}</SheetTitle>{selected.note&&<p className="detail-note">{selected.note}</p>}
    <h3>Клубника</h3><RadioGroup value={draft.variantId} onValueChange={chooseVariant} className="variant-options" aria-label="Вариант клубники">{forFamily(selected.id).filter(v=>!v.includedBerry||draft.variantId===v.id).map(v=><label key={v.id} className={draft.variantId===v.id?'variant-option selected':'variant-option'}><RadioGroupItem value={v.id}/><span>{v.includedBerry?'Свежая · с украшением':v.type==='fresh'?'Свежая':'Сублимированная'}<strong>{money(v.price)}</strong></span></label>)}</RadioGroup>
    {selected.designs.length>1&&<><h3>Оформление</h3><div className="design-options">{selected.designs.filter(id=>!(id==='A06'&&activeVariant.type==='fd')).map(id=><button className={draft.design===id?'design selected':'design'} key={id} aria-label={`Оформление ${id}${id==='A06'?', 1790 рублей':''}`} aria-pressed={draft.design===id} onClick={()=>{if(selected.id==='SET-12')chooseVariant(id==='A06'?'SET-12-A06':activeVariant.type==='fd'?'SET-12-FD':'SET-12-FRESH');else setDraft({...draft,design:id});}}><img src={photoUrl(id)} alt={'Оформление '+id} width={80} height={80} loading="lazy"/>{id==='A06'&&<small>1 790 ₽</small>}{draft.design===id&&<span className="design-check"><Check size={12}/></span>}</button>)}</div></>}
    <h3>Дополнить подарок</h3>{activeVariant.includedBerry?<div className="included-row"><Check size={19}/><span>Ягодное украшение уже включено</span></div>:<><label className="addon-row"><Checkbox checked={draft.berry!=='none'} onCheckedChange={checked=>setDraft({...draft,berry:checked?'blueberry':'none'})}/><span>Целая голубика или малина</span><strong>+200 ₽</strong></label>{draft.berry!=='none'&&<RadioGroup className="berry-options" value={draft.berry} onValueChange={berry=>setDraft({...draft,berry})} aria-label="Ягодное украшение"><label><RadioGroupItem value="blueberry"/>Голубика</label><label><RadioGroupItem value="raspberry"/>Малина</label></RadioGroup>}</>}
    <label className="addon-row"><Checkbox checked={withText} onCheckedChange={checked=>setWithText(checked===true)}/><span>Шоколадная надпись</span><strong>+250 ₽</strong></label>{withText&&<label className="inscription-input">Текст надписи<input maxLength={100} value={draft.inscription} placeholder="Например: С днём рождения!" onChange={e=>setDraft({...draft,inscription:e.target.value})}/></label>}<p className="detail-explanation">Оформление на фото — ориентир. Цвета и полную комплектацию согласуем перед оплатой. Крошка и посыпка не добавляют ягодную доплату.</p><div className="quantity-row"><span>Количество</span><Stepper value={draft.quantity} onChange={quantity=>setDraft({...draft,quantity})} label="количество"/></div>{error&&<p role="alert" className="error-message">{error}</p>}
   </div></div><div className="sheet-action"><button className="primary" onClick={add}>В корзину<span>{money(draftTotal)}</span></button></div>
  </>}</SheetContent></Sheet>
  <Sheet open={!!review} onOpenChange={isOpen=>{if(!isOpen&&!sendingRef.current){setReview('');setError('');setSentId('');}}}><SheetContent side="bottom" className="review-sheet" showCloseButton={false}><div className="sheet-top"><SheetTitle>{sentId?'Заявка передана':'Проверьте заявку'}</SheetTitle><button className="icon-button" disabled={sending} onClick={()=>{setReview('');setError('');setSentId('');}} aria-label="Закрыть заявку"><X size={21}/></button></div><div className="review-body"><SheetDescription>{sentId?'Номер заявки: '+sentId+'. Менеджер согласует детали в Telegram.':canSend?'Передадим заявку менеджеру и покажем подтверждение здесь.':standalone?'Скопируйте заявку и отправьте нам в Telegram. Согласуем оформление и время получения.':'Заявка готова к копированию. Для отправки откройте каталог кнопкой Telegram-бота.'}</SheetDescription><textarea className="order-preview" readOnly value={review} aria-label="Текст заявки"/>{error&&<p role="alert" className="error-message">{error}</p>}{canSend&&!sentId&&<button className="primary" disabled={sending} onClick={send}>{sending?'Передаём заявку…':'Отправить заявку'}<ArrowRight size={18}/></button>}<button className={canSend?'secondary':'primary'} onClick={copy}><Copy size={18}/> Скопировать заявку</button>{standalone&&<a className="secondary" href="https://t.me/deliberry_msk" target="_blank" rel="noopener noreferrer">Открыть наш Telegram<ArrowRight size={18}/></a>}<p className="checkout-note">Заявка не означает подтверждённый заказ. Оплата — после согласования.</p></div></SheetContent></Sheet>
  {notice&&<div role="status" className="toast"><Check size={17}/>{notice}</div>}
 </div>;
}
